export const CONFIG = {
  TOTAL_LAPS: 3,
  ROAD_WIDTH: 10,
  CURB_WIDTH: 1,
  CURB_BOUNCE: 0.35,

  MAX_SPEED: 32,
  MAX_REVERSE: 10,
  ACCEL: 14,
  BRAKE_DECEL: 26,
  FRICTION: 6,
  GRASS_FRICTION: 22,
  GRASS_MAX_SPEED: 12,
  STEER_RATE: 2.4,

  CHECKPOINT_COUNT: 6,
};
